spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://config:8888"
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://auth-service:5000
            predicates:
              - Path=/uaa/**
          - id: account-service
            uri: lb://account-service
            predicates:
              - Path=/accounts/**
          - id: statistics-service
            uri: lb://statistics-service
            predicates:
              - Path=/statistics/**
          - id: notification-service
            uri: lb://notification-service
            predicates:
              - Path=/notifications/**

server:
  port: 4000
