spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  security:
    oauth2:
      client:
        registration:
          account-service:
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
        provider:
          account-service:
            token-uri: http://auth-service:5000/uaa/oauth2/token

server:
  servlet:
    context-path: /accounts
  port: 6000
