logging:
  level:
    org.springframework.security: INFO

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    host: rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
