spring:
  data:
    mongodb:
      host: statistics-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
